In [1]:
import numpy as np

# numpy 数字化python，研究数据
# 快捷键执行代码shift+enter

In [2]:
# 列表[1,2,3,4,5]
l = [1,2,3,4,5]
print("打印列表",l)
print("打印列表", l[0])

打印列表 [1, 2, 3, 4, 5]
打印列表 1


In [3]:
print('取出两个数据',l[0:2]) #左闭右开
#print('取出两个数据',l[3,4]) #TypeError: list indices must be integers or slices, not tuple

取出两个数据 [1, 2]


In [4]:
# 创建numpy数组np.array(列表)
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr[[2,3]] #numpy可以自由的取多个数据

array([3, 4])

In [6]:
arr >= 3

array([False, False,  True,  True,  True])

In [7]:
cond = arr >= 3
cond
arr[cond]

array([3, 4, 5])

# 不同的创建方式

In [8]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros(shape =5)

array([0., 0., 0., 0., 0.])

In [10]:
np.full(shape=10,fill_value=3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [11]:
np.random.randint(0,100,size=10)

array([26, 55, 73,  0, 13, 96,  3, 34, 67, 22])

In [12]:
np.random.randn(10)#正态分布，平均值是0，标准差是1

array([ 1.04713135, -0.23880098,  0.70652253, -1.70586807,  1.01091261,
        0.44672529,  0.82941118, -0.59516579, -0.1602789 , -0.27973125])

In [13]:
np.linspace(1,99,50)#等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [14]:
np.set_printoptions(suppress=True)#不显示科学计数法
np.logspace(0,10,base=2,num=11)#等比数列,shift+tab可以看参数

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [15]:
np.random.randint(0,10,size=(3,5))

array([[3, 0, 0, 3, 0],
       [6, 4, 9, 1, 7],
       [4, 0, 8, 9, 3]])

In [16]:
np.random.randint(0,10,size=(2,3,4))

array([[[0, 0, 4, 5],
        [5, 9, 1, 0],
        [2, 1, 6, 1]],

       [[8, 6, 5, 1],
        [8, 9, 1, 7],
        [9, 8, 5, 4]]])

# 数据查看

In [21]:
arr = np.random.random(size=(3,5))
arr

array([[0.48088647, 0.13015406, 0.99773912, 0.19811397, 0.66978178],
       [0.52406021, 0.05557238, 0.4524001 , 0.77465727, 0.00565481],
       [0.09139791, 0.56683453, 0.40525653, 0.31861941, 0.01874544]])

In [22]:
arr.shape

(3, 5)

In [23]:
arr.dtype

dtype('float64')

In [24]:
arr.size

15

In [25]:
arr.ndim

2

In [26]:
arr.itemsize

8