In [1]:
import numpy as np

# numpy 数字化python，研究数据
# 快捷键执行代码shift+enter

In [2]:
# 列表[1,2,3,4,5]
l = [1,2,3,4,5]
print("打印列表",l)
print("打印列表", l[0])

打印列表 [1, 2, 3, 4, 5]
打印列表 1


In [3]:
print('取出两个数据',l[0:2]) #左闭右开
#print('取出两个数据',l[3,4]) #TypeError: list indices must be integers or slices, not tuple

取出两个数据 [1, 2]


In [4]:
# 创建numpy数组np.array(列表)
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr[[2,3]] #numpy可以自由的取多个数据

array([3, 4])

In [6]:
arr >= 3

array([False, False,  True,  True,  True])

In [7]:
cond = arr >= 3
cond
arr[cond]

array([3, 4, 5])

# 不同的创建方式

In [8]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros(shape =5)

array([0., 0., 0., 0., 0.])

In [10]:
np.full(shape=10,fill_value=3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [11]:
np.random.randint(0,100,size=10)

array([97, 63, 70, 90, 25, 94, 28, 87, 53, 64])

In [12]:
np.random.randn(10)#正态分布，平均值是0，标准差是1

array([-0.38285893, -0.58689199,  1.16765503, -1.27959516, -1.42587913,
       -0.52581999,  0.78906873,  2.47386659,  0.2762819 , -0.85214182])

In [13]:
np.linspace(1,99,50)#等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [14]:
np.set_printoptions(suppress=True)#不显示科学计数法
np.logspace(0,10,base=2,num=11)#等比数列,shift+tab可以看参数

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [15]:
np.random.randint(0,10,size=(3,5))

array([[7, 7, 5, 9, 7],
       [9, 0, 9, 4, 4],
       [9, 8, 0, 1, 9]])

In [16]:
np.random.randint(0,10,size=(2,3,4))

array([[[4, 6, 3, 3],
        [3, 4, 1, 4],
        [2, 7, 6, 1]],

       [[5, 7, 6, 3],
        [6, 8, 5, 6],
        [9, 5, 4, 2]]])

# 数据查看

In [17]:
arr = np.random.random(size=(3,5))
arr

array([[0.08193441, 0.24408382, 0.03869483, 0.12510419, 0.80125815],
       [0.42899163, 0.56818162, 0.27068934, 0.80288841, 0.60222755],
       [0.50963982, 0.99490015, 0.57050292, 0.6423689 , 0.49510708]])

In [18]:
arr.shape

(3, 5)

In [19]:
arr.dtype

dtype('float64')

In [20]:
arr.size

15

In [21]:
arr.ndim

2

In [22]:
arr.itemsize

8

# 文件IO操作

In [23]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
for i in range(0,10,3):
    print(i)

0
3
6
9


In [25]:
[i for i in range(0,10,2)]#列表生成式

[0, 2, 4, 6, 8]

In [26]:
arr = np.arange(0,10,2)
np.save('./data1.npy', arr)

In [27]:
np.load('./data1.npy')

array([0, 2, 4, 6, 8])

In [28]:
arr2 = np.logspace(0,10,base=2,num=11)

In [29]:
np.savez('./data2.npz', x=arr, y=arr2)

In [30]:
np.load('./data2.npz')['x']

array([0, 2, 4, 6, 8])

In [31]:
np.load('./data2.npz')['y']

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

# 数据类型

In [32]:
np.array([2,4,5],dtype=np.int16)

array([2, 4, 5], dtype=int16)

In [33]:
arr = np.random.randint(0,100,size=(100,50), dtype=np.int8)
np.save('data3int8',arr)

In [34]:
arr = np.random.randint(0,100,size=(100,50), dtype=np.int64)
np.save('data3int64',arr)

In [35]:
arr1 = np.arange(-128,128,dtype=np.int8)
arr1


array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [36]:
arr1 = np.arange(-128,128,dtype=np.uint8)
arr1

/tmp/ipykernel_581/770431717.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -128 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr1 = np.arange(-128,128,dtype=np.uint8)
/tmp/ipykernel_581/770431717.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -127 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr1 = np.arange(-128,128,dtype=np.uint8)


array([128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  5

In [37]:
arr1.dtype

dtype('uint8')

In [38]:
#转换数据类型
arr1.astype(np.float32)

array([128., 129., 130., 131., 132., 133., 134., 135., 136., 137., 138.,
       139., 140., 141., 142., 143., 144., 145., 146., 147., 148., 149.,
       150., 151., 152., 153., 154., 155., 156., 157., 158., 159., 160.,
       161., 162., 163., 164., 165., 166., 167., 168., 169., 170., 171.,
       172., 173., 174., 175., 176., 177., 178., 179., 180., 181., 182.,
       183., 184., 185., 186., 187., 188., 189., 190., 191., 192., 193.,
       194., 195., 196., 197., 198., 199., 200., 201., 202., 203., 204.,
       205., 206., 207., 208., 209., 210., 211., 212., 213., 214., 215.,
       216., 217., 218., 219., 220., 221., 222., 223., 224., 225., 226.,
       227., 228., 229., 230., 231., 232., 233., 234., 235., 236., 237.,
       238., 239., 240., 241., 242., 243., 244., 245., 246., 247., 248.,
       249., 250., 251., 252., 253., 254., 255.,   0.,   1.,   2.,   3.,
         4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,
        15.,  16.,  17.,  18.,  19.,  20.,  21.,  2

# 数组运算

In [39]:
nd = np.random.randint(0,10,size=(3,5))
nd

array([[9, 5, 5, 4, 5],
       [7, 4, 5, 1, 0],
       [6, 1, 2, 1, 9]])

In [40]:
nd - 5

array([[ 4,  0,  0, -1,  0],
       [ 2, -1,  0, -4, -5],
       [ 1, -4, -3, -4,  4]])

In [41]:
nd ** 2

array([[81, 25, 25, 16, 25],
       [49, 16, 25,  1,  0],
       [36,  1,  4,  1, 81]])

In [42]:
np.power(nd,3)

array([[729, 125, 125,  64, 125],
       [343,  64, 125,   1,   0],
       [216,   1,   8,   1, 729]])

In [43]:
nd/2

array([[4.5, 2.5, 2.5, 2. , 2.5],
       [3.5, 2. , 2.5, 0.5, 0. ],
       [3. , 0.5, 1. , 0.5, 4.5]])

In [44]:
nd%2

array([[1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1]])

In [45]:
nd // 2

array([[4, 2, 2, 2, 2],
       [3, 2, 2, 0, 0],
       [3, 0, 1, 0, 4]])

In [46]:
nd > 2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False, False, False,  True]])

In [47]:
nd == 0

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [48]:
nd == 4

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [49]:
nd+=100
nd

array([[109, 105, 105, 104, 105],
       [107, 104, 105, 101, 100],
       [106, 101, 102, 101, 109]])

In [50]:
nd == 207

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [51]:
nd == 0 # *= -=不支持/=

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [52]:
nd//=1

# 索引，切片和迭代

## 一维数组索引和切片

In [53]:
arr = np.random.randint(0,100,size=10)
arr

array([99, 68, 62, 93, 62, 67, 24, 30, 89, 52])

In [54]:
arr[2]

62

In [55]:
arr[[0,3,5]]

array([99, 93, 67])

In [56]:
arr[3:6]

array([93, 62, 67])

In [57]:
arr[3:6:2]#从3到6，步长为2

array([93, 67])

In [58]:
arr[::2]

array([99, 62, 62, 24, 89])

In [59]:
arr[::-1]

array([52, 89, 30, 24, 67, 62, 93, 62, 68, 99])

## 二维数组的索引和切片

In [60]:
arr= np.random.randint(0,100,size=(3,5))
arr

array([[34, 99, 33, 62, 49],
       [96, 99, 92, 51, 65],
       [52, 26, 62, 77, 31]])

In [61]:
arr[0,2]

33

In [62]:
arr[1,[1,2]]

array([99, 92])

In [63]:
arr[[1,2],[3,4]]

array([51, 31])

In [64]:
arr[[1,2],3:]#第二行和第三行的第四列第五列数据，索引和切片配合

array([[51, 65],
       [77, 31]])

In [68]:
arr[[0,2]][:,[3,4]]

array([[62, 49],
       [77, 31]])

In [69]:
arr[2,2]=1024
arr

array([[  34,   99,   33,   62,   49],
       [  96,   99,   92,   51,   65],
       [  52,   26, 1024,   77,   31]])

## 花式索引

In [2]:
import numpy as np
arr = np.random.randint(0,100,size=20)
arr

array([ 8, 98, 82, 77, 81, 42, 67, 76, 45, 58, 21, 17, 92, 37, 38, 15, 53,
       80,  7, 28])

In [3]:
arr[[3,5,7]]

array([77, 42, 76])

In [4]:
arr > 60

array([False,  True,  True,  True,  True, False,  True,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False])

In [5]:
arr[arr>60]

array([98, 82, 77, 81, 67, 76, 92, 80])

In [11]:
cond1 = arr < 30 
cond2 = arr > 80
arr[cond1 | cond2]

array([], dtype=int64)

In [10]:
arr[cond]

array([98, 82, 81, 92])