# 创建一个长度为10的唯一全为0的ndarray的对象，然后让第五个元素等于1

In [1]:
import numpy as np

In [2]:
arr = np.zeros(10,dtype='int')

In [3]:
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [5]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
arr = arr[::-1] # 颠倒元素
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
arr = np.full(shape=(10,10),fill_value=0,dtype=np.int64)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
arr[[0,-1]] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
arr = np.random.random(size=(10,10))
display(arr)
print('最大值',arr.max())
print('最小值',arr.min())

array([[0.89696505, 0.69816239, 0.36846131, 0.1555776 , 0.30628096,
        0.54402912, 0.27125631, 0.56349329, 0.059232  , 0.99311829],
       [0.59540337, 0.28568539, 0.12633742, 0.96989046, 0.7938038 ,
        0.55117803, 0.96470013, 0.84953366, 0.3813602 , 0.94944127],
       [0.43358118, 0.81781609, 0.36840789, 0.97097118, 0.4279031 ,
        0.17111352, 0.36975852, 0.80857767, 0.95746159, 0.00946999],
       [0.9572701 , 0.18069766, 0.91420516, 0.81045414, 0.09480563,
        0.74984945, 0.54542229, 0.36081999, 0.26654503, 0.20637944],
       [0.07027506, 0.47212056, 0.06878082, 0.78257018, 0.76903433,
        0.94940034, 0.40796038, 0.97362897, 0.42379613, 0.70901157],
       [0.75910292, 0.02871791, 0.75047182, 0.70350538, 0.02845451,
        0.70509439, 0.77803959, 0.89998088, 0.85265661, 0.420835  ],
       [0.05266924, 0.93706961, 0.34223141, 0.88631802, 0.10992512,
        0.71198084, 0.16217   , 0.33496051, 0.14038749, 0.20642032],
       [0.93586165, 0.02798731, 0.3664738

最大值 0.9964439504219612
最小值 0.009469988571069177


In [2]:
import numpy as np
arr = np.full(shape=(5,5),fill_value=3.14)
arr

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
arr2 = np.arange(0,5)
arr2
arr[:] = arr2
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [8]:
arr = np.linspace(0,1,12) # 等差
display(arr)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [21]:
np.set_printoptions(suppress=True)
np.logspace(-1,10,base=4,num=11) #等比

array([      0.25      ,       1.14869835,       5.27803164,
            24.25146506,     111.4304721 ,     512.        ,
          2352.53423103,   10809.40880505,   49667.00045141,
        228209.6068647 , 1048576.        ])

In [22]:
arr = np.random.randn(10) 
print('未排序: ', arr)

未排序:  [-0.55065904 -0.17192178 -1.57712187 -1.84335324  2.18526848 -0.97401658
  1.24778669  0.28482622  0.18886311 -0.42497993]


In [23]:
arr2 = np.sort(arr)
print('排序后: ', arr2)

排序后:  [-1.84335324 -1.57712187 -0.97401658 -0.55065904 -0.42497993 -0.17192178
  0.18886311  0.28482622  1.24778669  2.18526848]
