# 索引切片

In [2]:
import numpy as np
np2 = np.random.randint(-5,15,size=(5,6))
np2

array([[ 8,  6, 13, 12,  8,  5],
       [ 9, 12, 13, 12, 11, -4],
       [14, 10, -4, -2, -2,  5],
       [-4,  9, 11, 14,  9,  3],
       [-4, -5, -1, -4,  9,  0]])

In [3]:
np2[[1,3]]

array([[ 9, 12, 13, 12, 11, -4],
       [-4,  9, 11, 14,  9,  3]])

In [4]:
np2[:,[1,3,5]]

array([[ 6, 12,  5],
       [12, 12, -4],
       [10, -2,  5],
       [ 9, 14,  3],
       [-5, -4,  0]])

In [7]:
np2[[1,3,4],[1,3,5]] #成对出现

array([12, 14,  0])

In [12]:
np2[[1,3]][:,[1,3,5]]

array([[12, 12, -4],
       [ 9, 14,  3]])

In [16]:
index = np.ix_([1,3],[1,3,5])
np2[index] #相当于np2[[1,3]][:,[1,3,5]]

array([[12, 12, -4],
       [ 9, 14,  3]])

# 形状改变

In [6]:
import numpy as np

In [7]:
nd2 = np.random.randint(0,100,size=(3,4))

In [8]:
display(nd2)

array([[87, 39, 49, 61],
       [25, 83, 84, 55],
       [79, 80, 60, 80]])

## reshape

In [9]:
display(nd2.reshape(4,3)) #数据重塑reshape

array([[87, 39, 49],
       [61, 25, 83],
       [84, 55, 79],
       [80, 60, 80]])

In [10]:
print('2行6列:')
display(nd2.reshape(2,6))

2行6列:


array([[87, 39, 49, 61, 25, 83],
       [84, 55, 79, 80, 60, 80]])

In [11]:
display(nd2.reshape(-1,6)) # -1表示，最后算，相当于x*6=3*4--》x=2，适合不关心总数，灵活，自动算

array([[87, 39, 49, 61, 25, 83],
       [84, 55, 79, 80, 60, 80]])

In [12]:
display(nd2.reshape(-1)) #等于12=3*4

array([87, 39, 49, 61, 25, 83, 84, 55, 79, 80, 60, 80])

In [ ]:
nd2.reshape(3,5) # 不行，必须是3*4=12

## 叠加

In [17]:
arr1 = np.random.randint(0,10,size=(2,4))
arr2 = np.random.randint(-5,5,size=(3,4))
display(arr1,arr2)
np.concatenate([arr1,arr2])

array([[3, 3, 0, 7],
       [7, 6, 2, 3]])

array([[ 1, -5, -3,  0],
       [ 0, -5, -2,  2],
       [-3,  3,  4, -5]])

array([[ 3,  3,  0,  7],
       [ 7,  6,  2,  3],
       [ 1, -5, -3,  0],
       [ 0, -5, -2,  2],
       [-3,  3,  4, -5]])

In [18]:
arr1 = np.random.randint(0,10,size=(3,5))
arr2 = np.random.randint(-5,5,size=(3,4))
display(arr1,arr2)
np.concatenate([arr1,arr2],axis=1) # axis=0代表行叠加，=1代表列叠加，-1表示倒着数 

array([[1, 8, 0, 5, 1],
       [4, 9, 5, 7, 7],
       [3, 1, 9, 4, 7]])

array([[-5,  1,  2, -2],
       [ 3,  0, -5, -1],
       [-1, -4,  3, -2]])

array([[ 1,  8,  0,  5,  1, -5,  1,  2, -2],
       [ 4,  9,  5,  7,  7,  3,  0, -5, -1],
       [ 3,  1,  9,  4,  7, -1, -4,  3, -2]])

## 拆分

In [26]:
nd = np.random.randint(0,100,size=(6,9))
display(nd)
# 行拆分
np.split(nd, 3)

array([[59, 14, 47, 79,  4, 57, 60, 99, 62],
       [59, 30, 69, 83, 78, 68, 22, 88, 16],
       [36, 34, 10, 45, 66, 91, 74, 26, 96],
       [28, 13, 95, 62, 34, 78, 31, 52, 39],
       [92, 31, 99, 28, 24, 38, 64, 67,  7],
       [22, 65, 60,  7, 65, 91, 55, 54, 37]])

[array([[59, 14, 47, 79,  4, 57, 60, 99, 62],
        [59, 30, 69, 83, 78, 68, 22, 88, 16]]),
 array([[36, 34, 10, 45, 66, 91, 74, 26, 96],
        [28, 13, 95, 62, 34, 78, 31, 52, 39]]),
 array([[92, 31, 99, 28, 24, 38, 64, 67,  7],
        [22, 65, 60,  7, 65, 91, 55, 54, 37]])]

In [ ]:
# 列表，表示按节点进行拆分

In [28]:
np.split(nd,[1,4,5])
np.split(nd,[1,4,5], axis=1)

[array([[59],
        [59],
        [36],
        [28],
        [92],
        [22]]),
 array([[14, 47, 79],
        [30, 69, 83],
        [34, 10, 45],
        [13, 95, 62],
        [31, 99, 28],
        [65, 60,  7]]),
 array([[ 4],
        [78],
        [66],
        [34],
        [24],
        [65]]),
 array([[57, 60, 99, 62],
        [68, 22, 88, 16],
        [91, 74, 26, 96],
        [78, 31, 52, 39],
        [38, 64, 67,  7],
        [91, 55, 54, 37]])]

## 转置

In [32]:
A = np.random.randint(0,10,size=(3,5))
display(A)
display(A.reshape(5,3))
display(A.T) #列变行，行变列

array([[9, 6, 5, 2, 0],
       [7, 0, 7, 0, 2],
       [4, 6, 6, 7, 9]])

array([[9, 6, 5],
       [2, 0, 7],
       [0, 7, 0],
       [2, 4, 6],
       [6, 7, 9]])

array([[9, 7, 4],
       [6, 0, 6],
       [5, 7, 6],
       [2, 0, 7],
       [0, 2, 9]])

In [33]:
np.transpose(A,axes=[1,0])

array([[9, 7, 4],
       [6, 0, 6],
       [5, 7, 6],
       [2, 0, 7],
       [0, 2, 9]])

# 广播机制

In [39]:
arr1 = np.random.randint(0,10,size=(5,3))
arr2 = np.arange(1,4)
display(arr1,arr2)
arr1 + arr2 #五行+一行，广播机制arr2变身，变成了5份，每一份和每一行相加

array([[6, 3, 6],
       [7, 4, 9],
       [3, 4, 1],
       [6, 4, 3],
       [2, 8, 0]])

array([1, 2, 3])

array([[ 7,  5,  9],
       [ 8,  6, 12],
       [ 4,  6,  4],
       [ 7,  6,  6],
       [ 3, 10,  3]])

In [41]:
arr3 = np.random.randint(0,10,size = (4,5))
arr4 = arr3.mean(axis=1)
display(arr3,arr4)

array([[4, 4, 8, 6, 6],
       [8, 0, 0, 8, 4],
       [7, 5, 4, 9, 4],
       [3, 7, 5, 1, 5]])

array([5.6, 4. , 5.8, 4.2])

In [44]:
display(arr4.reshape(4,1))
arr3-arr4.reshape(4,1) #行相同或者列相同，可广播

array([[5.6],
       [4. ],
       [5.8],
       [4.2]])

array([[-1.6, -1.6,  2.4,  0.4,  0.4],
       [ 4. , -4. , -4. ,  4. ,  0. ],
       [ 1.2, -0.8, -1.8,  3.2, -1.8],
       [-1.2,  2.8,  0.8, -3.2,  0.8]])

# 通用函数

## 元素级函数

In [48]:
# abs、sqrt、square、exp、log、sin、cos、tan, maxinmum、minimum、all、any、inner、clip、round、 trace、ceil、floor
np.sin(np.pi/2) #90°

1.0

In [49]:
np.cos(np.pi/2).round(5) #保留5位小数

0.0

## where函数

In [50]:
np.sqrt(1024)

32.0

In [51]:
np.square(8)

64

In [55]:
def fun(x):
    return x**3
fun(3)
np.power(2,3)

8

In [56]:
def fun2(x):
    return x**(1/3)
fun2(27)
np.power(8,1/3)

2.0

In [62]:
x=np.array([1,5,2,9,3,6,8])
y=np.array([2,4,3,7,1,9,0])
np.maximum(x,y)

array([2, 5, 3, 9, 3, 9, 8])